# session默认30min 设置为600s
server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://47.106.219.116:3306/agile_homework?characterEncoding=utf8&useSSL=true
    username: agile_user
    password: agile_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 1000
      max-idle: 10
      min-idle: 5
      initial-size: 5
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      # 自动建表
      ddl-auto: update